raspberry:
  pi: 192.168.178.59

  apikey: 988112a4e198cc1211

spring:
  kafka:
    properties:
      security:
        protocol: SASL_SSL
      schema:
        registry:
          url: //{{ SR_ENDPOINT }}
      basic:
        auth:
          user:
            info: 3YDZZGUN522X36RE:akPFanFaRIHIDNybdqDrD0lWYiKAuJat+Q4x0DoaqeGn+XctWMegwqmjM0DRNJGI
          credentials:
            source: USER_INFO
      session:
        timeout:
          ms: 45000
    sasl:
      mechanism: PLAIN
      jaas:
        config: org.apache.kafka.common.security.plain.PlainLoginModule   required username='3YDZZGUN522X36RE'   password='akPFanFaRIHIDNybdqDrD0lWYiKAuJat+Q4x0DoaqeGn+XctWMegwqmjM0DRNJGI';
    bootstrap:
      servers: pkc-zpjg0.eu-central-1.aws.confluent.cloud:9092


