raspberry:
  pi: 192.168.178.59
  apikey: DDD33A6FDB

openweathermap:
  apikey: a1da74049732bdb7c6e882631724adac

spring:
  data:
    mongodb:
      uri: mongodb://sensor:gmw8z73@192.168.178.29:27017/?authSource=admin
      database: sensordb